[package]
name = "incremynt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
incremynt = { path = "../incremynt" }

anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
