[package]
name = "incremint-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
incremint = { path = "../incremint" }

anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
